### ISSUE TITLE
Checkmate bug once playing with AI

### ISSUE THREAD

**Issue by Kduszynska** [pawel150199/chess-ai#12]
With this configuration, after moving with white right bishop doing check to black, black wins

<img width="824" alt="Zrzut ekranu 2024-06-9 o 16 41 31" src="https://github.com/pawel150199/chess-ai/assets/103599351/a9beca9e-4116-46d4-804b-46ab76fbcbee">

**Comment by Kduszynska** [comment]
<img width="824" alt="xxx" src="https://github.com/pawel150199/chess-ai/assets/103599351/784a395a-8e1b-4be1-ba2a-bd464e297c45">

**Comment by pawel150199** [comment]
It was solved in #13.
