### ISSUE TITLE
Game is not finish after kill the king

### ISSUE THREAD

**Issue by Kduszynska** [pawel150199/chess-ai#4]
<img width="794" alt="Zrzut ekranu 2024-06-8 o 13 58 41" src="https://github.com/pawel150199/chess-ai/assets/103599351/26d28324-cd2d-445f-bc92-5d7ae4f2e5ae">

**Comment by pawel150199** [comment]
Partially fixed in MR #6 but still is not perfect. If we would like to improve this part, my recomendation is to try loop over all pieces and try to move. In that case checkmate should appear always without any required actions.

**Comment by pawel150199** [comment]
When the game has been ended following window should be visible 
![Screenshot 2024-06-08 at 19 48 47](https://github.com/pawel150199/chess-ai/assets/41188005/0848c99a-292d-425b-b77e-275a2f537319)

**Comment by pawel150199** [comment]
I am closing this bug. In case of another issue related to this we will open another issue ticket.
